name: riverbloc
description: >-
  BlocProvider implementation with riverpod as alternative to provider
version: 1.0.0-dev.3
homepage: https://github.com/kranfix/riverbloc/tree/master/packages/riverbloc
repository: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ">=7.2.0 <9.0.0"
  flutter:
    sdk: flutter
  meta: ^1.3.0
  riverpod: ^1.0.0-dev.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0
  #flutter_coverage_badge: ^0.0.1+1

flutter:
