name: riverbloc
description: >-
  BlocProvider implementation with riverpod as alternative to provider,
  similar to StateNotifierProvider
version: 1.0.0-dev.5
homepage: https://github.com/kranfix/riverbloc/tree/master/packages/riverbloc
repository: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ">=7.2.1 <9.0.0"
  meta: ^1.3.0
  riverpod: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  #flutter_coverage_badge: ^0.0.1+1

flutter:
