name: riverbloc
description: >-
  BlocProvider implementation with riverpod as alternative to provider
version: 0.1.0
homepage: https://github.com/kranfix/riverbloc/tree/master/packages/riverbloc
repository: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^0.8.0
  bloc: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flutter_coverage_badge: ^0.0.1+1

flutter:
