name: riverbloc
description: >-
  BlocProvider implementation with riverpod as alternative to provider
version: 0.2.2
homepage: https://github.com/kranfix/riverbloc/tree/master/packages/riverbloc
repository: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^0.13.1
  bloc: ^7.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.0
  #flutter_coverage_badge: ^0.0.1+1

flutter:
