name: riverbloc
description: >-
  BlocProvider implementation with riverpod as alternative to provider,
  similar to StateNotifierProvider
version: 2.0.0-dev.0
homepage: https://github.com/kranfix/riverbloc/tree/master/packages/riverbloc
repository: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ">=8.0.0 <9.0.0"
  meta: ^1.3.0
  riverpod: ^2.0.0-dev.0

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.4
  very_good_analysis: ^2.4.0
  #flutter_coverage_badge: ^0.0.1+1

flutter:
