name: riverbloc
description: >-
  BlocProvider implementation with riverpod as alternative to provider,
  similar to StateNotifierProvider
version: 2.0.0-dev.3
homepage: https://github.com/kranfix/riverbloc/tree/master/packages/riverbloc
repository: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ">=8.1.0 <9.0.0"
  meta: ^1.7.0
  riverpod: ^2.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.3
  very_good_analysis: ^3.0.0
  #flutter_coverage_badge: ^0.0.1+1

flutter:
