name: flutter_timer
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  riverbloc: ^2.0.0
  equatable: ^2.0.3
  wave: ^0.2.0

dependencies_overrides:
  riverbloc:
    path: ../../packages/riverbloc

flutter:
  uses-material-design: true
