name: example
description: An example for riverbloc with Flutter.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.2.0
  riverbloc:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
