name: bloc_counters
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1
  flutter_hooks_bloc: ^0.15.0
  flutter_hooks: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
