name: flutter_hooks_bloc
description: >-
  A flutter_bloc reimplementation based on flutter_hooks
  with the same API.
version: 0.15.0
homepage: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_bloc: ^7.0.1
  bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.2
  #flutter_coverage_badge: ^0.0.1+1

flutter:
