name: flutter_hooks_bloc
description: >-
  A flutter_bloc reimplementation based on flutter_hooks
  with the same API.
version: 0.16.0
homepage: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  bloc: ^7.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_hooks: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0
  #flutter_coverage_badge: ^0.0.1+1

flutter:
