name: flutter_hooks_bloc
description: >-
  A flutter_bloc reimplementation based on flutter_hooks
  with the same API.
version: 0.5.0
homepage: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.13.1
  flutter_bloc: ^6.0.1
  bloc: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flutter_coverage_badge: ^0.0.1+1

flutter:
