name: flutter_hooks_bloc
description: >-
  A flutter_bloc reimplementation based on flutter_hooks
  with the same API.
version: 0.13.0
homepage: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.13.1
  flutter_bloc: ^7.0.0-nullsafety.3
  riverbloc: ^0.2.1
  bloc: ^7.0.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  #flutter_coverage_badge: ^0.0.1+1

flutter:
